### PR TITLE
A30 acceptance update

### PR DESCRIPTION
**Pull request by ibaldin**
Added comments in the code to support A30 and A40 GPUs (and tested on CERN).

Added an optional cell to install nat64 configuration to download CUDA from IPv6 only sites.

### CODE REVIEW

**Comment by kthare10** [comment]
Could you also please update: `requirements.txt` to use version `1.4.1`?

**Comment by ibaldin** [comment]
Done

**Review by kthare10 — APPROVED** [review]
Looks good

**Comment by ibaldin** [comment]
Do you want to merge/tag - I don't know what the process is here.

**Comment by kthare10** [comment]
I'll merge and tag.

**Pull request merged**
