### PR TITLE
Added slice private key password prompt to fablib notebooks.

### PR DESCRIPTION
**Pull request by 842Mono**

### CODE REVIEW

**Comment by 842Mono** [comment]
The branch now also has the p4 notebook working with fablib.

**Comment by kthare10** [comment]
@842Mono Could you please review the code again based on my previous comment? If I don't receive any response within a week, we may proceed to close the pull request.

**Comment by 842Mono** [comment]
> @842Mono Could you please review the code again based on my previous comment? If I don't receive any response within a week, we may proceed to close the pull request.

Hi. Unfortunately I'm not able to work nowadays, more or less. I won't be able to review the code currently. Maybe something very quick, I can do. What exactly do you need me to do? I can't find other comments from you. What do you want me to review?

...about 6 months ago, you also asked me to do something, but I didn't do it. I didn't forget, but I wasn't able to do what you wanted me to do. Apologies. Not sure if I'll follow up there at some point in the future.

**Comment by kthare10** [comment]
@842Mono - Many of the pull requests are not synchronized with the latest FABLIB interface. Therefore, I don't have a specific comment but perhaps a comprehensive request to revise examples to align with the current FABLIB interface. I completely understand if this might not be feasible. In that case, I encourage you to create a GitHub issue detailing the feature you aimed to address with this pull request. We can then collaborate to address it. Apologies for the persistence.

**Pull request closed without merging**
