### PR TITLE
A notebook that shows how to install slate on top of a kubernetes clu…

### PR DESCRIPTION
**Pull request by 842Mono**
…ster deployed using the manual method.

### CODE REVIEW

**Comment by kthare10** [comment]
@842Mono - This notebook uses Native API interface, would it be possible to update this to work with the latest fablib api?

**Comment by 842Mono** [comment]
Sure, will do my best.

**Comment by 842Mono** [comment]
[three_notebooks_for_debugging.zip](https://github.com/fabric-testbed/jupyter-examples/files/13258750/three_notebooks_for_debugging.zip)

Hi. Not sure why I'm getting an authentication error. I've restarted the jupyter hub server.

**Comment by kthare10** [comment]
@842Mono - Could you please check if you are still a member of any active project? Also, please post on lear.fabric-testbed.net if you are still not able to access JupyterHub just to avoid spamming this Issue.

**Comment by kthare10** [comment]
@842Mono Could you please review the code again based on my previous comment? If I don't receive any response within a week, we may proceed to close the pull request.

**Pull request closed without merging**
