### PR TITLE
Added MTU testing acceptance test

### PR DESCRIPTION
**Pull request by ibaldin**
Using @yoursunny mtu testing code (https://github.com/yoursunny/fabric/blob/5d434c3117314730a9ab38ffd4eefcab70f13779/util/mtu.py), this is an acceptance test (also documented in Confluence). 

@kthare10 will you merge as appropriate?

### CODE REVIEW

**Review by kthare10 — APPROVED** [review]
Looks good

**Comment by yoursunny** [comment]
This part is duplicated twice, in Step 4 and Step 6:

```py
re_loss = re.compile('([\d]+)% packet loss')
re_rtt = re.compile('rtt.*([.\d]+)/([.\d]+)/([.\d]+)/[.\d]+ ms')
width_mtu = 4
width_rtt = 4
width_td = width_mtu + width_rtt
```

**Comment by ibaldin** [comment]
D'oh.

**Comment by ibaldin** [comment]
Will fix on another PR

**Pull request merged**
