### PR TITLE
pmacctd_integration

### PR DESCRIPTION
**Pull request by pilfg**
This research project focuses on integrating the pmacctd tool into the FABRIC testbed and includes the development of a comprehensive tutorial featuring various experiments.

### CODE REVIEW

**Comment by kthare10** [comment]
@pilfg - Could you please sign the commits? Please see the instructions above.

**Comment by kthare10** [comment]
@pilfg - Looks like your old commit is still unsigned. Could you please sign that as well?
If it's easier, just create a new branch and add your changes and use signed commits.
Also, another suggestion is to clear output of the cells in the notebook.


In addition, where you are using `node.execute()` which installs packages. I'd suggest to either pass in the log file to capture the output or run it as quietly as below:

Quiet Execution:
```
stdout, stderr = node.execute("command ", quiet=False, output_file=f"{node.get_name()}.log");
```
Redirect output to Logs:
```
stdout, stderr = node.execute("command ", quiet=True);
```

**Comment by pilfg** [comment]
Dear Komal Thareja,

I have created a new branch and made a signed commit with my changes.
Additionally, I have updated the use of node.execute() to run package
installations in quiet mode.

Before I proceed with creating the pull request (PR), are there any other
improvements or modifications needed for the notebook?

Thank you for your guidance.

Best regards,
Pilar Fernandez

**Comment by kthare10** [comment]
@pilfg - I think everything else looks good. Please also remember to clear the output of the cells in the notebook.
Another suggestion - (not a mandatory change) is to use variables for parameters such as IP address which users may want to change on the top, so it's easier to customize your notebook.

**Pull request closed without merging**
