### PR TITLE
NEU workflow for FPGA flashing

### PR DESCRIPTION
**Pull request by mcevik0**
Notebook for adaptation of the [NEU workflow](https://github.com/OCT-FPGA/P4OpenNIC_Public/tree/main/FABRIC-P4)

### CODE REVIEW

**Review by kthare10 — APPROVED** [review]
Looks good!

**Comment by kthare10** [comment]
@mcevik0 - Could you please enable signed commits for your account? This branch has unsigned commits. I am merging this for now but would recommend to enable signed commits.

**Comment by mcevik0** [comment]
I just noticed that. Among multiple terminals probably I lost track of the work and committed without signing. I'm not sure if I can do it after this point, probably I will create a new PR (and a new branch).

**Comment by mcevik0** [comment]
Actually, I noticed that you merged the branch. I think it's fine this time, thank you.

**Comment by kthare10** [comment]
For now, I have merged this one so we should be okay.

**Pull request merged**
